# Generated by Django 4.1.1 on 2022-09-24 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutricional',
            name='quantidade_porcao',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='Porção'),
        ),
    ]
