# Generated by Django 4.1.1 on 2022-10-14 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_alter_nutricional_quantidade_porcao'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutricional',
            name='alto_acucar',
            field=models.BooleanField(default=False, verbose_name='Alto Açúcar Adicionado'),
        ),
        migrations.AddField(
            model_name='nutricional',
            name='alto_gordura',
            field=models.BooleanField(default=False, verbose_name='Alto Gordura Saturada'),
        ),
        migrations.AddField(
            model_name='nutricional',
            name='alto_sodio',
            field=models.BooleanField(default=False, verbose_name='Alto Sódio'),
        ),
        migrations.AlterField(
            model_name='composicaoitem',
            name='quantidade_ingrediente',
            field=models.FloatField(default=0.0, verbose_name='Quantidade do Ingrediente'),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='acucar_adicionado',
            field=models.FloatField(default=0.0, verbose_name='Açúcares Adicionados'),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='acucar_total',
            field=models.FloatField(default=0.0, verbose_name='Açúcares Totais'),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='carboidrato',
            field=models.FloatField(default=0.0, verbose_name='Carboidratos'),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='fibra_alimentar',
            field=models.FloatField(default=0.0, verbose_name='Fibra Alimentar'),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='gordura_saturada',
            field=models.FloatField(default=0.0, verbose_name='Gorduras Saturadas'),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='gordura_total',
            field=models.FloatField(default=0.0, verbose_name='Gorduras Totais'),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='gordura_trans',
            field=models.FloatField(default=0.0, verbose_name='Gorduras Trans'),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='proteina',
            field=models.FloatField(default=0.0, verbose_name='Proteinas'),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='quantidade_medida_caseira',
            field=models.FloatField(default=0.0, verbose_name='Quantidade da Medida Caseira'),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='quantidade_porcao',
            field=models.FloatField(default=0.0, verbose_name='Porção'),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='sodio',
            field=models.FloatField(default=0.0, verbose_name='Sódio'),
        ),
        migrations.AlterField(
            model_name='nutricional',
            name='valor_energetico',
            field=models.FloatField(default=0.0, verbose_name='Valor Energético'),
        ),
        migrations.AlterField(
            model_name='rendimentoitem',
            name='quantidade_rendimento',
            field=models.FloatField(default=0.0, verbose_name='Quantidade da Medida Caseira'),
        ),
    ]
